### ISSUE TITLE
lat e long retornadas estão erradas

### ISSUE THREAD

**Issue by oabreu04** [cusco/ctt#2]
Boas, 

Estava a usar esta lista num pequeno projeto e dei conta que algumas coordenadas estão a vir erradas para certos códigos postal.
Exemplo: 
O código postal 9545-011 (ilha de S. Miguel zona da Bretanha)  vem com as coordenadas (38,7113116, -9,1982123) que correspondem a Lisboa, mais precisamente à zona do Alto da Ajuda.
Verificando o google maps ,neste exemplo as coordenadas corretas seriam (37.850323,-25.7797354).
O que poderá estar a gerar este erro? Algum bug?
Posso dar mais exemplos de casos errados se for necessário validar outras situações.

**Comment by cusco** [comment]
Olá @oabreu04,

Antes de responder, gostaria de perceber a fonte de dados que estás a usar: directamente do ficheiro CTT.sql ou se usaste os scripts PHP para popular a tua própria base de dados?

**Comment by oabreu04** [comment]
Usei diretamente o csv que partilhaste, o ctt-lat-lng.csv

**Comment by cusco** [comment]
Experimenta estes dados, certamente terás ainda alguns erros, mas a maior parte corrigidos: https://github.com/cusco/ctt/blob/master/CTT_postcodes_w_lat_lng.zip

**Comment by oabreu04** [comment]
Obrigado! 
O exemplo que te apresentei já aprece com as coordenadas corretas, mas tal como mencionaste ainda apanho alguns erros. 
Ex: 
cod_postal: 4770-330 vem com as coordenadas (38.7838132, -9.1114244) quando deveria aparecer com algo semelhante a (40.576, -8.325)

Cumprimentos!

**Comment by cusco** [comment]
> Obrigado!
> O exemplo que te apresentei já aprece com as coordenadas corretas, mas tal como mencionaste ainda apanho alguns erros.
> Ex:
> cod_postal: 4770-330 vem com as coordenadas (38.7838132, -9.1114244) quando deveria aparecer com algo semelhante a (40.576, -8.325)
> 
> Cumprimentos!

Boas,

Existe uma coluna com "scanned address" e outra com "found address", referentes à pesquisa que foi feita no google geolocation, e à resposta que este devolveu - podes verificar essas colunas..

De qualquer modo, não tenho trabalhado com isto, já não tenho intenção de acertar mais nada

**Comment by oabreu04** [comment]
Tranquilo! Percebo perfeitamente que agora tenhas outras prioridades 😉
O trabalho que desenvolveste não deixa de ser bastante útil para muita gente.
