### ISSUE TITLE
Exportar para JSON

### ISSUE THREAD

**Issue by jfoclpf** [cusco/ctt#3]
Fixe, parabéns pelo teu trabalho. Achas que podes exportar isso tudo para JSON?
Para o meu projecto gratuito e open source também aqui no github :)
www.geoptapi.org

Agradecido

**Comment by cusco** [comment]
Olá João, obrigado!

Como mencionei anteriormente, não tenho planeado dedicar aqui mais tempo. Mas visto que já existe um export em formato [SQL](https://github.com/cusco/ctt/blob/master/CTT.sql) e outro em [CSV](https://github.com/cusco/ctt/blob/master/ctt-lat-lng-csv.zip) - não deve ser difícil converter para json, certo?

**Comment by jfoclpf** [comment]
tens razão
